---
- name: include_vars
  include_vars: vars.yml
  no_log: true
  tags: proxy

- name: sso token
  ovirt_auth:
    hostname: "{{ rhv_engine_fqdn }}"
    username: "{{ rhv_username }}"
    password: "{{ rhv_password }}"
    ca_file: /etc/pki/ovirt-engine/ca.pem
  tags: 
    - proxy
    #- clean-proxy
    
- name: create Trilio Backup role 
  ovirt_role:
    auth: "{{ ovirt_auth }}"
    name: TrilioBackup
    description: role created for backup user
    administrative: true
  tags: proxy


- name: create Trilio Monitor role 
  ovirt_role:
    auth: "{{ ovirt_auth }}"
    name: TrilioMonitor
    description: role created for monitor user
    administrative: true
  tags: proxy

- name: create Trilio Restore role
  ovirt_role:
    auth: "{{ ovirt_auth }}"
    name: TrilioRestore
    description: role created for restore user
    administrative: true
  tags: proxy
  
- name: create Trilio Backup Admin role
  ovirt_role:
    auth: "{{ ovirt_auth }}"
    name: TrilioBackupAdministrator
    description: role created for backupadmin
    administrative: true
  tags: proxy

