---
- name: include_vars
  include_vars: vars.yml
  tags: proxy

- name: sso token
  ovirt_auth:
    hostname: "{{ rhv_engine_fqdn }}"
    username: "{{ rhv_username }}"
    password: "{{ rhv_password }}"
    ca_file: /etc/pki/ovirt-engine/ca.pem
  tags: 
    - proxy
    #- clean-proxy
    
- name: create trilioBackup role with login permissions
  ovirt_role:
    auth: "{{ ovirt_auth }}"
    name: TrilioBackup
    description: role created for backup user
    administrative: true
    permits:
      - create_disk
  tags: proxy


- name: create trilioMonitor role with login permissions
  ovirt_role:
    auth: "{{ ovirt_auth }}"
    name: TrilioMonitor
    description: role created for monitor user
    administrative: true
  tags: proxy

- name: craete TrilioRestore roles
  ovirt_role:
    auth: "{{ ovirt_auth }}"
    name: TrilioRestore
    description: role created for restore user
    administrative: true
    permits:
      - create_disk
      - attach_disk
      - sparsify_disk
      - run_vm
      - create_vm
      - create_template
      #- edit_properties_template
  tags: proxy
  
- name: create monitor role
  ovirt_role:
    auth: "{{ ovirt_auth }}"
    name: TrilioBackupAdministrator
    description: role created for backupadmin
    administrative: true
    permits:
      - manipulate_permissions
      - manipulate_users
      - manipulate_roles
      - create_disk
      - delete_disk
      - attach_disk
      - sparsify_disk
      - create_cpu_profile
      - delete_cpu_profile
      - update_cpu_profile
      - assign_cpu_profile
      #- create_vm_pool
      #- delete_vm_pool
      - reboot_vm
      - stop_vm
      - run_vm
      - create_vm
      - create_instance
      - delete_vm
      - create_template
      - delete_template
      - copy_template
      #- manipulate_status
      #- edit_network
  tags: proxy

# - name: Remove TrilioBackup role with clean-proxy
#   ovirt_role:
#     auth: "{{ ovirt_auth }}"
#     name: TrilioBackup
#     state: absent
#   tags: clean-proxy

# - name: Remove TrilioMonitor role with clean-proxy
#   ovirt_role:
#     auth: "{{ ovirt_auth }}"
#     name: TrilioMonitor
#     state: absent
#   tags: clean-proxy

# - name: Remove TrilioRestore role with clean-proxy
#   ovirt_role:
#     auth: "{{ ovirt_auth }}"
#     name: TrilioRestore
#     state: absent
#   tags: clean-proxy

# - name: Remove TrilioBackupAdministrator role with clean-proxy
#   ovirt_role:
#     auth: "{{ ovirt_auth }}"
#     name: TrilioBackupAdministrator
#     state: absent
#   tags: clean-proxy
