---
# tasks file for test

- name: Read variables from triliovault-nodes file
  include_vars: /etc/ansible/group_vars/triliovault-nodes
  tags:
    - daemon
    - proxy
    - clean-daemon


- name: Remove imageio if already present
  file:
    path: /opt/ovirt-imageio
    state: absent
  tags: 
    - daemon
    - clean-daemon

- name: check daemon version
  command: yum info ovirt-imageio-daemon
  register: daemon_version
  tags: 
    - daemon
    - clean-daemon 

 
- name: Check if fury.repo file exixts
  stat:
    path: /etc/yum.repos.d/fury.repo   
  register: fury_status
  tags:
    - daemon
    - clean-daemon 

- name: Remove fury.repo file if exists
  file:
    state: absent
    path: /etc/yum.repos.d/fury.repo
  when: fury_status.stat.exists
  tags:
    - daemon
    - clean-daemon

- name: Touch fury.repo file 
  copy:
    dest: "/etc/yum.repos.d/fury.repo"
    content: |
      [fury]
      name=Gemfury Private Repo
      baseurl=https://yum.fury.io/triliodata-rhv/
      enabled=1
      gpgcheck=0
  tags: 
    - daemon

- name: check rpm installation
  shell: rpm -qa ovirt-imageio_1.6
  register: output
  tags:
    - daemon
    - clean-daemon

- name: Remove rpm if alreday installed
  shell: rpm -e ovirt-imageio_1.6
  when: output.stdout | regex_search('ovirt-imageio_1.6')
  tags: 
    - daemon
    - clean-daemon

- name: Install rpm from Gemfury
  shell: dnf -y install ovirt-imageio_1.6
  when: daemon_version.stdout | regex_search('2.0.3')
  tags:
    - daemon

- name: Untar venv in ovirt-imageio
  shell: tar -pxvzf virtenv.tar.gz
  args:
    chdir: /opt/ovirt-imageio
  tags:
    - daemon


- name: Untar new venv
  shell: tar -pxvzf venv.tar.gz
  args:
    chdir: /opt/ovirt-imageio/daemon/datamover
  tags: daemon


- name: Change directory permissions
  file:
    path: /opt/ovirt-imageio
    state: directory
    owner: vdsm
    group: kvm
    recurse: yes
  tags: daemon


- name: Check if redis service is running
  service:
    name: redis
    state: started
  register: redis_status
  tags: daemon

- name: Adding a redis config entry to not to save redis data
  command: redis-cli config set stop-writes-on-bgsave-error no
  tags: daemon

- name: Activate 5000 port in firewall
  firewalld:
    port: 5000/tcp
    permanent: yes
    state: enabled
  tags: daemon

# - name: Activate 5000 port in firewall
#   shell: firewall-cmd --zone=public --add-port=5000/tcp
#   tags: daemon

- name: Stopping playbook execution as redis in not installed
  fail: msg="Please install redis" 
  when: redis_status.state == "stopped"
  tags: daemon
   
- name: do the encode
  shell: echo {{ storage_nfs_export | b64encode }}
  register: encoded_nfs_share
  tags: 
    - daemon
    - clean-daemon

- set_fact:
    encoded_nfs_share: "{{ encoded_nfs_share.stdout }}"
  tags: 
    - daemon
    - clean-daemon

- name: Creating mount path
  set_fact:
    mount_path: "{{ vault_data_directory }}/{{ encoded_nfs_share }}"
  tags: 
    - daemon
    - clean-daemon

- name: Check mount point {{ mount_path }}
  command: mountpoint {{ mount_path }}
  register: mount_state
  failed_when: False
  changed_when: False
  tags: daemon

- name: debug
  when: mount_state.stdout == "{{ mount_path }} is a mountpoint"
  debug:
    msg: "{{ mount_path }} is a mountpoint"
  tags: daemon

- name: debug
  when: mount_state.stdout == "{{ mount_path }} is not a mountpoint"
  debug:
    msg: "{{ mount_path }} is not a mountpoint"
  tags: daemon

- name: Unmounting existing mount path
  mount: 
    path: "{{ mount_path }}"
    state: unmounted
  when: mount_state.stdout == "{{ mount_path }} is a mountpoint"
  tags: daemon

- name: Creating mount path directory if it does not exist
  file:
    path: "{{ mount_path }}"
    state: directory
    owner: vdsm
    group: kvm
    recurse: yes
  tags: daemon
  
- name: Mount NFS volume
  command: mount -t nfs -o rw,nolock,soft,intr,timeo=180,vers=3 {{ storage_nfs_export }} {{ mount_path }}
  tags: daemon


- name: Generating workload using UUID
  set_fact:
    workload_id: "{{ 1000 | random | to_uuid | lower }}"
    snapshot_id: "{{ 1000 | random | to_uuid | lower }}"
    vm: "{{ 1000 | random | to_uuid | lower }}"
    vm_resource: "{{ 1000 | random | to_uuid | lower }}"
  tags: daemon


- name: Checking NFS read/write permissions for VDSM user
  file:
    path: "{{ mount_path }}/workload_{{ workload_id }}/snapshot_{{ snapshot_id}}/vm_{{ vm }}/vm_resource_{{ vm_resource }}"
    state: file
    owner: vdsm
    group: kvm
    state: directory
  tags: daemon


- name: Creating test file to check permissions for VDSM user
  file: 
    path: "{{ mount_path }}/workload_{{ workload_id }}/snapshot_{{ snapshot_id}}/vm_{{ vm }}/vm_resource_{{ vm_resource }}/test"
    state: touch
    owner: vdsm
    group: kvm
  tags: daemon

- name: Remove directory struture created to test NFS validation
  file:
    path: "{{ mount_path }}/workload_{{ workload_id }}"
    state: absent
    owner: vdsm
    group: kvm
  tags: daemon

- name: Test for vdsm entry in /etc/sudoers 
  shell: grep "^vdsm ALL = NOPASSWD" /etc/sudoers
  register: test_sudoers
  ignore_errors: yes
  tags: daemon

- name: Adding vdsm entry in /etc/sudoers
  lineinfile:
    line: "vdsm ALL = NOPASSWD: ALL"
    insertafter: EOF
    dest: /etc/sudoers
  when: test_sudoers.stdout == ""
  tags: daemon
  
- name: Test for NFS mount entry in fstab 
  shell: grep "^{{ storage_nfs_export }} {{ mount_path }}" /etc/fstab
  register: test_grep
  ignore_errors: yes
  tags: daemon

- name: Adding NFS mount entry in fstab
  lineinfile:
    line: "{{ storage_nfs_export }} {{ mount_path }} nfs rw,nolock,soft,intr,timeo=180,vers=3 36 36"
    insertafter: EOF
    dest: /etc/fstab
  when: test_grep.stdout == ""
  tags: daemon

- name: Check if ovirt-datamover directory exists
  stat:
    path: /etc/ovirt-datamover
  register: my_folder
  tags: daemon
 
- name: echo if directory already existed
  debug:
    msg: "the ovirt-datamover directory is already existed"
  when: my_folder.stat.exists
  tags: daemon
 
- name: Create ovirt-datamover directory if not exists
  file:
    path: /etc/ovirt-datamover
    state: directory
    mode: 0755
    group: kvm
    owner: vdsm
  when: my_folder.stat.exists == false
  tags: daemon

- name: Check if datamover.conf exists
  stat: path=/etc/ovirt-datamover/datamover.conf
  register: status
  tags: daemon

- debug: var=status
  tags: daemon

- name: Touch datamover.conf file if does not exist
  file:
    state: touch
    path: /etc/ovirt-datamover/datamover.conf
    owner: vdsm
    group: kvm
    mode: 0755
  when: status.stat.exists == false
  tags: daemon

- name: Remove mount path from datamover.conf befor daemon config
  ini_file:
    path: /etc/ovirt-datamover/datamover.conf
    section: nfs_config
    state: absent
  tags: daemon

- name: Append empty line to datamover config file
  lineinfile:
    line: ''
    insertafter: EOF
    dest: /etc/ovirt-datamover/datamover.conf
  with_items:
  - "\n"
  tags: daemon

- name: Append encoded nfs share to datamover conf file
  lineinfile:
    line: "[nfs_config]"
    insertafter: EOF
    dest: /etc/ovirt-datamover/datamover.conf
  tags: daemon

- name: Append encoded nfs share to file
  lineinfile:
    line: "nfs_share = {{ storage_nfs_export }}"
    insertafter: EOF
    dest: /etc/ovirt-datamover/datamover.conf
  tags: daemon

- name: Append mount path to file
  lineinfile:
    line: "mount_path = {{ mount_path }}"
    insertafter: EOF
    dest: /etc/ovirt-datamover/datamover.conf
  tags: daemon


- name: Remove mount path from datamover.conf for clean-daemon
  ini_file:
    path: /etc/ovirt-datamover/datamover.conf
    section: nfs_config
    state: absent
  tags: clean-daemon

- name: Stop the existing ovirt-datamover service
  service:
    name: ovirt-datamover
    state: stopped
  ignore_errors: yes
  register: ovirt_datamover
  tags: 
    - daemon
    - clean-daemon

- name: Stop Celery worker daemon if already running
  service:
    name: ovirt_celery
    state: stopped
  ignore_errors: yes
  tags: 
    - daemon
    - clean-daemon

- debug:
    msg: "ovirt-datamover is stopped"
  ignore_errors: yes
  when: ovirt_datamover.state == "stopped"
  tags: daemon

- name: Add controller key to authorized_keys
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags: daemon


- name: Create directory to record daemon logs
  file:
    path: /var/log/imageio_daemon
    state: directory
    owner: vdsm
    group: kvm
    recurse: yes
  tags: daemon

- name: Setup logrotate.d scripts
  template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}{{ item.name }}"
  with_items: "{{ logrotate_scripts }}"
  when: logrotate_scripts is defined
  tags:
    - daemon


# Adding host entry in /etc/host of TVM

- name: register target ip
  set_fact:
    target_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  register: target_ip
  tags: daemon


- debug:
    var: target_ip
  tags: daemon

- name: Getting fqdn of host
  shell: hostname
  register: fqdn
  tags: daemon

- name: Removing existing host entry from /etc/hosts before adding new
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{ target_ip }}'
    state: absent
  tags: daemon


- name: Adding fqdn value to /etc/hosts of TVM
  lineinfile:
    path: /etc/hosts
    regexp: '(^\s+{{ target_ip }}([\w=/\-\.\,\_]+)*)\s*$'
    line: "{{ target_ip }} {{ fqdn.stdout }}"
  delegate_to: 127.0.0.1
  tags: daemon

- name: Create directory to record logs
  file:
    path: /var/log/ovirt_celery
    state: directory
    owner: vdsm
    group: kvm
    recurse: yes
  tags: daemon

- name: Check if ovirt-datamover.service file exists
  stat:
    path: /usr/lib/systemd/system/ovirt-datamover.service
  register: datamover_status
  tags:
     - daemon
     - clean-daemon

- name: Remove ovirt-datamover.service file if exists
  file:
    state: absent
    path: /usr/lib/systemd/system/ovirt-datamover.service
  when: datamover_status.stat.exists
  tags:
     - daemon
     - clean-daemon

# - name: Check if Daemon was already configured.
#   stat:
#     path: /usr/lib/systemd/system/ovirt-datamover-original.service
#   register: stat_result
#   tags: 
#     - daemon
#     - clean-daemon
  

# - name: Rename existing ovirt-datamover service file to original before replacing
#   copy:
#     src: /usr/lib/systemd/system/ovirt-datamover.service
#     dest: /usr/lib/systemd/system/ovirt-datamover-original.service
#     remote_src: yes
#   become: true
#   when: stat_result.stat.exists == True
#   tags: daemon

# - name: Remove service file if already present
#   file:
#     path: /usr/lib/systemd/system/ovirt-datamover.service
#     state: absent
#   when: stat_result.stat.exists == True
#   tags: 
#     - daemon

# - name: Replace file with original contents
#   copy:
#     src: /usr/lib/systemd/system/ovirt-datamover-original.service
#     dest: /usr/lib/systemd/system/ovirt-datamover.service
#     remote_src: yes
#   become: true
#   when: stat_result.stat.exists == True
#   tags: clean-daemon


# - name: Remove service file if already present
#   file:
#     path: /usr/lib/systemd/system/ovirt-datamover.service
#     state: absent
#   when: stat_result.stat.exists == True
#   tags:
#     - clean-daemon


# - name: Remove service file if already present
#   file:
#     path: /usr/lib/systemd/system/ovirt-datamover.service
#     state: absent
#   when: stat_result.stat.exists == True
#   tags:
#     - clean-daemon


# - name: Remove service file if already present
#   file:
#     path: /usr/lib/systemd/system/ovirt-datamover.service
#     state: absent
#   when: stat_result.stat.exists == True
#   tags:
#     - clean-daemon

  
# - name: Remove original service file if already present
#   file:
#     path: /usr/lib/systemd/system/ovirt-datamover-original.service
#     state: absent
#   when: stat_result.stat.exists == True
#   tags: clean-daemon

- name: Copy the datamover service file
  copy:
    src: /opt/ovirt-imageio/service-files/ovirt-datamover.service
    dest: /usr/lib/systemd/system/ovirt-datamover.service
    remote_src: yes
    mode: u=rw,g=r,o=r
  tags: daemon

- name: Activate the celery virtualenv
  shell: source /opt/ovirt-imageio/virtenv/bin/activate
  tags: daemon

- name: Remove celery service file if already present
  file:
    path: /usr/lib/systemd/system/ovirt_celery.service
    state: absent
  tags: 
    - daemon
    - clean-daemon

- name: Copy the celery service file
  copy:
    src: /opt/ovirt-imageio/service-files/ovirt_celery.service
    dest: /usr/lib/systemd/system/ovirt_celery.service
    remote_src: yes
    owner: vdsm
    group: kvm
    mode: u=rw,g=r,o=r
  tags: daemon

- name: Systemctl daemon reload
  command: systemctl daemon-reload
  tags: 
    - daemon
    - clean-daemon

- name: Start ovirt-datamover Service
  service:
    name: ovirt-datamover
    enabled: yes
    state: started
  tags: 
    - daemon

- name: Start ovirt-celery Service
  service:
    name: ovirt_celery
    enabled: yes
    state: started
  tags: 
    - daemon

# - name: Start Celery worker service
#   command: systemctl start ovirt_celery
#   tags: daemon

# - name: Enable Celery worker service
#   command: systemctl enable ovirt_celery
#   tags: daemon

- name: Unmounting existing mount path
  mount: 
    path: "{{ mount_path }}"
    state: unmounted
  tags: clean-daemon

- name: Remove NFS mount entry in fstab
  lineinfile:
    line: "{{ storage_nfs_export }} {{ mount_path }} nfs rw,nolock,soft,intr,timeo=180,vers=3 36 36"
    state: absent
    dest: /etc/fstab
  tags: clean-daemon

# clean-daemon remove datamover service file, celery,datamover.conf, ovirt-datamover directory
- name: Remove datamover-service,celery, datamover.conf files while clean-daemon
  file:
    path: '{{ item }}'
    state: absent
  with_items:
     - /usr/lib/systemd/system/ovirt-datamover.service
     - /usr/lib/systemd/system/ovirt_celery.service
     - /etc/ovirt-datamover/datamover.conf
     - /etc/ovirt-datamover
  tags: clean-daemon


# proxy deployment

- name: Add controller key to authorized_keys
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags: proxy

- name: Check if trilio-plugin-resources directory exists
  stat:
    path: /usr/share/ovirt-engine/ui-plugins/trilio-plugin-resources
  register: ui_status
  tags:
     - proxy
     - clean-proxy

- name: Remove directory trilio-plugin-resources if present
  file:
    state: absent
    path: /usr/share/ovirt-engine/ui-plugins/trilio-plugin-resources
  when: ui_status.stat.exists
  tags:
     - proxy
     - clean-proxy


- name: Check if trilio-plugin.json file exists
  stat:
    path: /usr/share/ovirt-engine/ui-plugins/trilio-plugin.json
  register: file_status
  tags:
     - proxy
     - clean-proxy

- name: Remove trilio-plugin.json file if exists
  file:
    state: absent
    path: /usr/share/ovirt-engine/ui-plugins/trilio-plugin.json
  when: file_status.stat.exists
  tags:
     - proxy
     - clean-proxy

- name: create directory trilio-plugin-resources
  file:
    path: /usr/share/ovirt-engine/ui-plugins/trilio-plugin-resources
    state: directory
  tags: proxy

- name: copy trilio-plugin-resources
  copy:
    src: /opt/stack/rhvgui-resources/trilio-plugin-resources/
    dest: /usr/share/ovirt-engine/ui-plugins/trilio-plugin-resources
    directory_mode: yes
  tags: proxy

- name: copy json file
  copy:
    src: /opt/stack/rhvgui-resources/trilio-plugin.json
    dest: /usr/share/ovirt-engine/ui-plugins/
  tags: proxy

- name: main | updating rhvgui config file for new react app
  action: template src=data.js.j2 dest=/usr/share/ovirt-engine/ui-plugins/trilio-plugin-resources/config.js
  tags:
    - proxy
# Added changes for adding ca.pem to /etc/workloadmgr of TVM

- name: Rename ca.pem to engine.pem
  shell: cp ca.pem engine.pem
  args:
    chdir: /etc/pki/ovirt-engine
  tags: proxy
 
- name: copy engine.pem to TVM
  fetch:
    src: /etc/pki/ovirt-engine/engine.pem
    dest: /etc/workloadmgr/
    flat: yes
  tags: proxy


- name: Remove engine.pem from manager
  shell: rm -f engine.pem
  args:
    chdir: /etc/pki/ovirt-engine
  tags: proxy





  